updated

diff --git a/scripts/group-branchout b/scripts/group-branchout
--- a/scripts/group-branchout
+++ b/scripts/group-branchout
@@ -13,6 +13,7 @@ pos1="$(indexof $project ':')"
 pos2="$(indexof $project '/')"
 projectGroup="${project:0:$pos1-1}"
 projectGitUrl="${project:$pos1}"
+projectOrg="${project:$pos1:$pos2-$pos1-1}"
 projectName="${project:$pos2}"
 
 test -z "${projectGroup}" && echo "Missing project group" && exit 77
@@ -20,13 +21,10 @@ test -z "${projectGitUrl}" && echo "Missing project git url" && exit 77
 test -z "${projectName}" && echo "Missing project name" && exit 77
 
 if [[ ! -d "./${projectGroup}/" ]]; then
-  mkdir -p "${projectGroup}"
+  echo "Cloning parent project from ${gitBaseUrl}:${projectOrg}/${projectGroup}.git"
+  git clone --depth=1 "${gitBaseUrl}:${projectOrg}/{projectGroup}.git" > /dev/null 2>&1|| echo "Could not checkout group repository"
+  if [[ ! -d "./${projectGroup}/.git" ]]; then
+    echo "No parent group project found for: ${projectGroup}"
+    mkdir -p "${projectGroup}"
+  fi
 fi
-
-if [[ ! -d "./${projectGroup}/${projectName}/.git" ]]; then
-  echo "Cloning project from ${gitBaseUrl}:${projectGitUrl}.git"
-  git clone "${gitBaseUrl}:${projectGitUrl}.git" "${projectGroup}/${projectName}"> /dev/null 2>&1|| echo "Could not checkout group repository"
-fi
-
-
-
diff --git a/scripts/project-branchout b/scripts/project-branchout
--- a/scripts/project-branchout
+++ b/scripts/project-branchout
@@ -11,7 +11,7 @@ projectGroup="${project:0:$pos1-1}"
 projectGitUrl="${project:$pos1}"
 projectName="${project:$pos2}"
 
-set -e
+set -e -x
 cd "$(dirname "$0")/.."
 
 if [[ -z "${project}" ]]; then
@@ -34,11 +34,11 @@ if [[ -d "./${projectGroup}/${projectName}/.git" ]]; then
   git pull --rebase origin > /dev/null 2>&1 || (echo -e "Failed: \033[31m${projectGroup}/${projectName}\033[0m \033[70D\033[70C\033[1m $( git pull --rebase origin 2>&1| head -n1)\033[0m")
 else
   cd "${projectGroup}"
-  echo -e "Cloning Project: \033[92m${projectGroup}/${projectName}\033[0m"
-  if git clone "${gitBaseUrl}/${projectName}.git" > /dev/null 2>&1; then
+  echo -e "Cloning Project: \033[92m${gitBaseUrl}:${projectGitUrl}.git\033[0m"
+  if git clone "${gitBaseUrl}:${projectGitUrl}.git" > /dev/null 2>&1; then
     cd "${projectName}"
     logProjectAction "Cloned"
   else
-    echo "Cloning failed: \033[31m${projectGroup}/${projectName}\033[0m"
+    echo -e "Cloning failed: \033[31m${gitBaseUrl}:${projectGitUrl}.git\033[0m"
   fi
 fi
